### ISSUE TITLE
Feature request: Only allow setting faction homes inside of a faction

### ISSUE THREAD

**Issue by CalXee** [ickerio/factions#1]
Feels like a nice balance features that I see other faction mods have. It also differentiate this more from regular /home mods.

**Comment by ickerio** [comment]
Great idea. I'll make an option in the config to either `disable`, `enable` or `limit_to_claims` the /home command

**Comment by ickerio** [comment]
In the `config.json` file, you can specify either `ANYWHERE`, `CLAIMS`, `DISABLED` defaulting to `CLAIMS`. 

`ANYWHERE` means a home can be set anywhere (previous behavior)
`CLAIMS` allows homes to only exist within a claim
`DISABLED` simply disables the /f home command altogether
