### ISSUE TITLE
Faction Display Doesn't Work

### ISSUE THREAD

**Issue by Charadon** [ickerio/factions#116]
### Expected behavior

When you walk into a faction territory, it says you're entering.

### Observed/actual behavior

No message displays on action bar.

### Steps/models to reproduce

User 1 claims land.
User 2 enters land.
User 1 nor 2 see any message on the action bar.

### Version

1.21

### Other

#30 suggests this was added. Therefore I think something broke in the code.

**Comment by BlueZeeKing** [comment]
This worked for me locally. Run `/f settings radar` to enable it

**Comment by Charadon** [comment]
> This worked for me locally. Run `/f settings radar` to enable it

I see it now. Is there a way to turn that on by default?

**Comment by BlueZeeKing** [comment]
No, but the setting doesn't get reset by server reboots.

**Comment by Charadon** [comment]
> No, but the setting doesn't get reset by server reboots.

Would you guys be willing to add an option in the config to turn it on globally? Because that's kind of a UX nightmare if someone isn't familiar with the mod. The faction system may as well not even exist to them without the radar on.
