### ISSUE TITLE
Factions.json doesn’t change anything about the server

### ISSUE THREAD

**Issue by hidrostix** [ickerio/factions#122]
### Expected behavior

The factions.json file in config doesn’t actually change anything about the mod.
Whenever I disabled echests connecting to the safe, it doesn’t do that
I also tried enabling and disabling other features like home set and it wouldn’t disable

### Observed/actual behavior

I tried checking console for problems but no error message was shown
The file did change but the file version on top did not, and any change to the file doesn’t change the mods properties

### Steps/models to reproduce

I think the description should be enough since there is no error message
Perhaps there is a dependancy that this mod needs or is it a different json file that i need to edit

### Version

1.21 fabric 

### Other

[factions.json](https://github.com/user-attachments/files/18240816/factions.json)

**Comment by ickerio** [comment]
Please post your factions.json file. When there is a misconfigured json file the mod will ignore it. It is likely you've made a mistake in it.

**Comment by hidrostix** [comment]
I added my factions file, had to try and find a way to download since I'm using a terminal and not a user friendly GUI for the server

**Comment by BlueZeeKing** [comment]
There is a syntax error in the config file. On line 18, when you set home to false, you also have to delete the curly brackets. The corrected version is: 

```json
{
  "version": 3,
  "power": {
    "base": 20,
    "member": 20,
    "claimWeight": 5,
    "deathPenalty": 10,
    "powerPerAlly": 0,
    "powerTicks": {
      "ticks": 12000,
      "reward": 5
    }
  },
  "safe": {
    "enderChest": false,
    "double": true
  },
  "home": false,
  "display": {
    "factionNameMaxLength": -1,
    "changeChat": true,
    "tabMenu": true,
    "nameBlackList": [
      "wilderness",
      "factionless"
    ],
    "powerMessage": true
  },
  "relationships": {
    "allyOverridesPermissions": true,
    "defaultGuestPermissions": [
      "USE_BLOCKS",
      "USE_ENTITIES"
    ]
  },
  "maxFactionSize": -1,
  "friendlyFire": true,
  "requiredBypassLevel": 4,
  "claimProtections": true
}
```

**Comment by hidrostix** [comment]
ahh I see, so I did get the sytax wrong, thanks!
