### ISSUE TITLE
Chat based chunk map

### ISSUE THREAD

**Issue by Metacinnabar** [ickerio/factions#13]
### Is your feature request related to a problem?

No issue here, but a suggestion to improving the efficiency of chunk claiming.

### Describe the solution you'd like.

When a command such as `/f claim map` is issued, it would show square cubes colored differently to what land is claimed. It is difficult to explain so I will provide an image at the end of the issue displaying how another faction plugin did it.

### Describe alternatives you've considered.

This could display who's claimed land it is, but that could be unbalanced.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

### Other

![image](https://user-images.githubusercontent.com/45357714/124865564-3ba09900-dffe-11eb-9c3a-8754b5d14a8e.png)
A screenshot of a spigot factions plugin had a claim map.

**Comment by ickerio** [comment]
This will be quite technically challenging to write but I'll certainly consider it in the future
