### ISSUE TITLE
Ability to use specific items in claims

### ISSUE THREAD

**Issue by GoodPro712** [ickerio/factions#14]
### Is your feature request related to a problem?

It is frustrating that I cannot eat or use rockets in someone else's claimed land.

### Describe the solution you'd like.

Allow players to use items such as food and rockets in claimed land by default, but add a config option for it in faction settings, possibly `/f modify eatInClaim true` or something similar.

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

### Other

N/A

**Comment by ickerio** [comment]
I ideally would like to keep the mod simple for players as I believe existing factions solutions in Spigot and Bukkit etc. try and do too much and confuse the player. I agree some items should be usable in claims and I will eventually rectify this but I may not be going down the path of being able to *configure* every little thing about your faction such as eating in claims.
