### ISSUE TITLE
Trying to break or build in a claim causes items and durability to be changed client side, and updating the stack visually restores it

### ISSUE THREAD

**Issue by CalXee** [ickerio/factions#15]
### Expected behavior

Trying to build in a claim would not cause the blocks in my inventory to visually count down, and breaking things with a tool shouldn't cause the tool to lose durability client side.

### Observed/actual behavior

Visually the stack count and durability decreases.

### Steps/models to reproduce

1. Go in a claim
2. Try to build or break block with a tool

### Version

Version 1.2.1

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by ickerio** [comment]
Hi, I'm aware of this issue and it is unintended behavior. However, I'm not entirely sure on the best way to go about solving this. If anyone knows how to send inventory update packets etc. I would love some input on this. Cheers for the issue
