### ISSUE TITLE
Friendly arrows and sweeping attacks hurt fellow faction members

### ISSUE THREAD

**Issue by ickerio** [ickerio/factions#18]
### Expected behavior

Faction members should not be able to damage each other

### Observed/actual behavior

Friendly arrows and sweeping attacks with swords hurt fellow faction members

### Steps/models to reproduce

- Shoot an arrow at a fellow faction member
- Use a sword to attack an entity close to a faction member and they'll receive damage through sweeping

### Version

Minecraft 1.17.1
Factions master branch

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by BlueZeeKing** [comment]
Fixed it!
