### ISSUE TITLE
Running info and list commands crashes server. "Exception in server tick loop"

### ISSUE THREAD

**Issue by PaulZappia** [ickerio/factions#24]
### Expected behavior

I expected to be able to use the commands with no issues.

### Observed/actual behavior

When I actually used the command/s, the server crashes immediately, giving me this error:
https://paste.ee/p/6Dwxx

### Steps/models to reproduce

1. Set up a faction
2. Run /f info or /f list

### Version

v1.3.0 for 1.17.0

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by ickerio** [comment]
You're using the wrong version of the mod. You're playing on 1.17.1 with the mod for version 1.17.0. [This](https://github.com/ickerio/factions/releases/tag/v1.3.0) is the version you need.
