### ISSUE TITLE
Feature request: Config file

### ISSUE THREAD

**Issue by CalXee** [ickerio/factions#3]
All values in the mod seems hardcoded and is pretty limiting given other similar mods offer a config.

4 chunks limit and extra 2 chunks per new faction member is very few and it being configurable not only fixes the issue but also lets for altering the balance of a faction server. Although I feel that should be raised much higher by default.

Toggle pvp between faction mates would also be nice.

**Comment by ickerio** [comment]
Great idea. I'm actually currently writing the config update and it should be done fairly soon. Other than what is in [the config Java file](https://github.com/ickerio/factions/blob/master/src/main/java/io/icker/factions/config/Config.java), and toggle PVP between faction mates, is there any other options you would like?

**Comment by CalXee** [comment]
Another useful feature is maybe making a faction claimed land never naturally spawn hostile mobs. Off by default.

**Comment by ickerio** [comment]
Hi, it's been implemented and I'll make a release on Github shortly. Simply make a `config.json` file with these values. If you do not specify a value, the default will be used. 

I plan on making a wiki in the coming days and better documenting this. 
| Value               | Description                                                                                 | Default        |
|---------------------|---------------------------------------------------------------------------------------------|----------------|
| basePower           | Power that every faction starts off with                                                    | 20             |
| memberPower         | Power gained per member in a faction                                                        | 20             |
| claimWeight         | Power required to hold one chunk                                                            | 10             |
| maxFactionSize      | Maximum number of members allowed in a faction (-1 for no limit)                            | -1             |
| safeTicksToWarp     | Minimum number of ticks to allow a player to warp after taking damage (1 second = 20 ticks) | 1000 (5 sec)   |
| powerDeathPenalty   | Power lost when killed by another player                                                    | -10            |
| ticksForPower       | The number of ticks a player must survive to recover their power                            | 12000 (10 min) |
| ticksForPowerReward | Power recovered after ticksForPower survival time                                           | 1              |
