### ISSUE TITLE
Enable / disable the chat feature

### ISSUE THREAD

**Issue by Topnitel** [ickerio/factions#39]
### Is your feature request related to a problem?

Since Factions overwrites the vanilla chat, mods like Fabric-Discord integration can't read the chat.

### Describe the solution you'd like.

An option in config.json to enable or disable the factions chat feature

### Describe alternatives you've considered.

An option to have Factions use the vanilla chat system for the global chat

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by PyPylia** [comment]
I also believe we can probably work to improve compatibility with other mods by implementing the mixin differently. But a toggle for it altogether would be nice.

**Comment by BlueZeeKing** [comment]
> I also believe we can probably work to improve compatibility with other mods by implementing the mixin differently.

I've been experimenting with the 1.19 snapshots and the new chat signing will require changing the chat handling in a way that should make it more compatible with mods.

**Comment by BlueZeeKing** [comment]
This has been added in the 1.19 branch
