### ISSUE TITLE
[Bug] Players can still open Storage Blocks in Claimed Land

### ISSUE THREAD

**Issue by GoodPro712** [ickerio/factions#4]
### Description
Players can still open chests and shulker boxes etc when that land is claimed by a faction.

**Comment by ickerio** [comment]
I've done a lot of play testing and am running this on a server with 30 people and have not ran into this. How are you able to replicate it?

**Comment by GoodPro712** [comment]
Sorry, but I'll get back to you in the morning.

**Comment by GoodPro712** [comment]
To replicate:
/f claim chunk
Get a player online or use a carpet bot (`/player test spawn`)
Have them open a chest in that chunk (`/player test use once` for carpet`)

They seem to be able to open the chest even if the land is claimed. I can let you know the ip of the server so you can come and test this out if you'd like to.

**Comment by ickerio** [comment]
Very strange behavior. Yes please add me on discord ickerio#1498 and we can discuss it there. Cheers!

**Comment by GoodPro712** [comment]
Was caused by outdated version*
