### ISSUE TITLE
New ways to claim

### ISSUE THREAD

**Issue by TheButterbrotMan** [ickerio/factions#40]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like.

I would like to apply for various claim options:

1. /autoclaim (When you walk through the chunk it is claimed)
2. /radclaim [chunks] [shape] (Claim a certain number of chunks with a predefined shape.)

### Describe alternatives you've considered.

There are no alternatives.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by PyPylia** [comment]
This has now been fixed in the latest dev version.
The commands `/f claim add [<size>] [force]`, `/f claim remove [<size>|all]` and `/f claim auto` have been added.
These will be released in the next release (most likely v2.0.0) coming out soon.
