### ISSUE TITLE
Keep empty fractions

### ISSUE THREAD

**Issue by TheButterbrotMan** [ickerio/factions#41]
### Is your feature request related to a problem?

If an admin wants to create a "SafeZone" and leaves it, the fraction is deleted.

### Describe the solution you'd like.

The possibility to create a "fake user" for a faction

or

a config in the faction that only admins can change

### Describe alternatives you've considered.

There are no alternatives.

### Agreements

- [ ] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by BlueZeeKing** [comment]
There is already an issue dedicated to this, #19. I'll add a comment to that to include this as a possible alternative.
