### ISSUE TITLE
Individual rights per claimed chunk

### ISSUE THREAD

**Issue by TheButterbrotMan** [ickerio/factions#43]
### Is your feature request related to a problem?

I don't want all players in the faction to have access to all claimed chunks. 

### Describe the solution you'd like.

A way to give faction owners the ability to secure a claim with a command and then add people to the claim like on a whitelist.

### Describe alternatives you've considered.

https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric

But i want your Factionsmod for my modpack.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by BlueZeeKing** [comment]
I think this system would work best with chunks only being available to a certain rank or above

**Comment by PyPylia** [comment]
This feature is very niche, and would require adding a lot of checks all over the codebase.

Due to this we've decided we won't be implementing this feature for the time being (though may implement it in the future).

**Comment by BlueZeeKing** [comment]
I will implement the per rank permissions but doing it for individuals would be two difficult
