### ISSUE TITLE
Change the name of a faction

### ISSUE THREAD

**Issue by TheButterbrotMan** [ickerio/factions#44]
### Is your feature request related to a problem?

I cannot rename factions.

### Describe the solution you'd like.

A command like /f name [NEW NAME] to rename a faction.

### Describe alternatives you've considered.

To rename a faction you currently have to leave it, lose all claimed chunks and have to create a new one...very cumbersome....

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by ickerio** [comment]
I like this idea. I'll close this issue and it can be further discussed in #46
