### ISSUE TITLE
New (simpler) commands

### ISSUE THREAD

**Issue by TheButterbrotMan** [ickerio/factions#46]
### Is your feature request related to a problem?

I find the current structure of the commands confusing and they somehow make an incomplete impression.

### Describe the solution you'd like.

First I write down the new commands for already existing commands, then new ones.

Change:

- [ ] /f home set -> /f sethome
- [ ] /f disband -> /f leave
- [ ] /f kickMember -> /f kick

New:

- [ ] /f name {new name} renames your faction.
> Explained in https://github.com/ickerio/factions/issues/44
- [ ] /f desc {description} sets your faction description.
> Self-explanatory.
- [ ] /f motd {message} sets the message of the day your faction members see when they log on.
> A simple motd.
- [ ] /f unsethome unsets your faction home.
> Deleting the home without adding a new one.
- [ ] /f help shows all comands of the mod.
> Self-explanatory.
- [ ] /f show {faction name} shows faction information.
> A detailed /f list, where for example the motd could be displayed, or all members.
- [ ] /f player {player name} shows player information.
> Which faction he belongs to, how much power he has, when he was last logged in.
- [ ] /f join {faction name} to join a faction you have been invited to.
> Self-explanatory.
- [ ] /f title {player name} {title} set player’s title. Use [formatting codes](https://minecraft.fandom.com/wiki/Formatting_codes) for color.
> For example [King] TheButterbrotMan

### Describe alternatives you've considered.

There are no alternatives.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by ickerio** [comment]
> /f home set -> /f sethome
>/f unsethome 

We won't be making these change as subcommands are much more memorable and organized

> /f disband -> /f leave

These are already two separate commands that serve a separate purpose

> /f desc {description} sets your faction description

This is possible sure, but we need to be careful with how many alias' we make as they can quickly become confusing

> /f help

Iirc the default `/help` command shows our faction commands

> /f show {faction name}

`/f info` should just be changed instead to have more information

> /f player {player name}

I like the idea of this though it should just show the players faction, no log in timestamps imo.

> /f join {faction name} 

This is already in the mod

> /f title {player name} {title} set player’s title. Use [formatting codes](https://minecraft.fandom.com/wiki/Formatting_codes) for color.

I think other mods should be used for this instead, soon-ish we should have better chat compatibility with other mods

However I definitely agree with the following additions and changes
> /f kickMember -> /f kick
> /f rename {new name}
> /f motd {message}

**Comment by ickerio** [comment]
Both rename and have been written and are coming in the next version. I'll do MOTD next

**Comment by ickerio** [comment]
Closing, added MOTD too in 68037cfdc56ef5fe87b074062eaf30012721beba
