### ISSUE TITLE
[Feature Request] Faction Chat

### ISSUE THREAD

**Issue by GoodPro712** [ickerio/factions#5]
### Description
Faction chat command that sends every message sent to chat into a private chat that only faction members can see.
For example: 
`/f chat` 
`You are now in faction chat`
Pretty self explanatory.

**Comment by ickerio** [comment]
Thanks! I've been thinking about adding this and plan to implement it within a few weeks.

**Comment by ickerio** [comment]
I've done a fair bit of thinking and have come up with the following idea regarding this mechanic.

Each player can toggle their chat to either `Focus`, `Faction`, or `Global`
`Focus` only send and receive messages from your faction
`Faction` receives all messages, sends to your faction only
`Global`  Receives all messages, sends to everyone

Your chat defaults to `Global` and can be changed with the `/f chat <option>` command. This saves over sessions but I could add an optional notification that tells the player what chat mode they're in as they join the server.

![image](https://user-images.githubusercontent.com/14541442/124733371-b5754b80-df46-11eb-882b-489379490006.png)

Above is how the chat would be formatted obviously replacing `Faction` with the faction name and red with the desired faction colour. The first line is the currently existing behavior for faction notifications seen in the claim, invite etc command. 

I welcome feedback or any changes to this proposal. Cheers!
