### ISSUE TITLE
Play sounds on actions

### ISSUE THREAD

**Issue by ickerio** [ickerio/factions#50]
### Is your feature request related to a problem?

Would be cool to have some audio feedback on certain commands and actions

### Describe the solution you'd like.

Audio feedback could go on

- claim add
- claim remove
- power gain
- power lose
- member join
- member leave

### Describe alternatives you've considered.

Having no sounds. This is a nice to have feature, sounds not necessary.

### Other

Should be togglable for each player and in the config file
Less is more, will get annoying if too many sounds

**Comment by PyPylia** [comment]
Could also have the config be an enum for different types of sounds. Eg. `NONE`, `WARNINGS`, `FACTION`, `ALL`.

**Comment by PyPylia** [comment]
This is now fixed.
