### ISSUE TITLE
Togglable claim protection

### ISSUE THREAD

**Issue by BlueZeeKing** [ickerio/factions#56]
### Is your feature request related to a problem?

You might not want to be able to break blocks but open doors

### Describe the solution you'd like.

Use a system like the fabric permissions api for more specific control

### Describe alternatives you've considered.

Add it to the config

**Comment by ickerio** [comment]
In my opinion this in more in the scope of mods land protection mods like [flan](https://www.curseforge.com/minecraft/mc-mods/flan) rather than pvp factions stuff. I think if we did do this, a config option would be most best to enforce this server wide.

**Comment by BlueZeeKing** [comment]
Completed by 11a7091aebaad0bd720640ab098e2c8b6e553934 d15a417a9bc293934e59cbcb6d655f7e0c96d7ba 1c3ad4a36ceab43ea0288a58f25e4ad1e594ff91 39f82df4dee9fc07c1b75a913d48cf71d87f6414 and fafa6181cb54a9b5706278ce2a3582ef82efc9a8
