### ISSUE TITLE
Config Json doesn't work

### ISSUE THREAD

**Issue by poseidoncarrot** [ickerio/factions#57]
### Expected behavior

The json working and the power levels changed

### Observed/actual behavior

The json not working and the power levels remain the un-configed ones

### Steps/models to reproduce

![image](https://user-images.githubusercontent.com/105404350/174134526-a05b4c7f-acbd-4e1b-a936-b33c4f5ace04.png)
The bottom 6 lines should be purple then red like the top 10 lines which then somehow breaks the entire json since the json doesn't work even with the correct naming

### Version

factions-mc1.18.2-1.5.0+.jar

**Comment by poseidoncarrot** [comment]
oh, the command list in the config section is wrong then since I directly copied and pasted the things besides changing a few things

![image](https://user-images.githubusercontent.com/105404350/174135975-c7243546-186f-4ef3-a72e-32470387af96.png)
 at the end of chat modification enabled

**Comment by poseidoncarrot** [comment]
Thank you for the help :)

**Comment by poseidoncarrot** [comment]
Just fixed it, and it still isn't working
![image](https://user-images.githubusercontent.com/105404350/174137147-fa0b6646-827f-4846-b1f1-f2817c283f96.png)

**Comment by BlueZeeKing** [comment]
Thanks for letting me know about the wiki, I just fixed it. Also, the color change is due to the value switching from a number to string

**Comment by BlueZeeKing** [comment]
Are you using the 1.18.2 version?

**Comment by BlueZeeKing** [comment]
Ah, the wiki is for the 1.19 version of the mod. [Here](https://github.com/ickerio/factions/wiki/Config/ae42e994e82e07f851851ef4079c482a0c31c2ab) is the older version of the wiki

**Comment by poseidoncarrot** [comment]
ah, I fixed it and restarted the server but for some reason the config is still in default mod
![image](https://user-images.githubusercontent.com/105404350/174138512-15d29694-9207-462d-b66b-1bec5dff7a10.png)
this is my config file, everything looks ok but it doesn't work for some reason

**Comment by BlueZeeKing** [comment]
The config file should be moved to factions/config.json

**Comment by poseidoncarrot** [comment]
it works now, tysm for the help :)
