### ISSUE TITLE
Faction Name Character Limits

### ISSUE THREAD

**Issue by FinchoZombie** [ickerio/factions#58]
### Is your feature request related to a problem?

I would like this to be added so players can't make huge faction tags.

![image](https://user-images.githubusercontent.com/31356909/176497326-b3891724-b1c1-413c-b618-7f3a01c6b3df.png)

### Describe the solution you'd like.

A config file addition such as 

  "maxTagSize": 5,
  
  5 Being max characters / letters

### Describe alternatives you've considered.

I didn't see any way to change this.

**Comment by FinchoZombie** [comment]
Limit the length of the name

**Comment by ickerio** [comment]
@BlueZeeKing Instead of having a truncated name I think just a maximum length of name would be a lot less complex and confusing

**Comment by BlueZeeKing** [comment]
replace with limiting name in ef81fd65653dad88096d903ae20747029b5ea8fd
