### ISSUE TITLE
Entering a faction chunk should display the title and description of the faction under the crosshair

### ISSUE THREAD

**Issue by CalXee** [ickerio/factions#6]
I might be doing something wrong, but I don't know how to get that to work. I tried entering a claimed chunk, and getting my friend to enter my claimed chunks and nothing is happening. I also therefore have no idea what faction description is used for.

Thank you for developing this mod! I've always loved factions and this lets me play on it in 1.17. :)

**Comment by ickerio** [comment]
Hi thanks for your support in raising these issues. I haven't yet planned this feature as there are some more critical things I was hoping to do first but I'll definitely add this to the TODO list. 

Faction description is shown in the `/f info` and `/f list` command when you hover your mouse over the faction name. You can also hover your mouse over the player count (`3/4`) to see the names of the players.

**Comment by GoodPro712** [comment]
Displaying this would be as simple as:
`/title @p title "\COLORCODE Entering FACTIONNAME"`
`/title @p subtitle "Faction description..."`
For example
![image](https://user-images.githubusercontent.com/45357714/124058837-79854680-da6d-11eb-9636-8b7b6c8c0841.png)
