### ISSUE TITLE
Cleaner config with nesting

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#62]
### Is your feature request related to a problem?

The config currently is confusing and complicated, through nesting this could be simplified, and more closely mimic other mods and plugins. This would require a custom GSON serializer/deserializer. Additionally, granular control over commands would be removed from the config. Instead, we'd redirect users to the Fabric Permission API integration.

### Describe the solution you'd like.

New config as follows:
```json
{
    "version": 3, // Bump version due to breaking changes
    "power": { // If not false, enable faction power
        "base": 20, // basePower
        "member": 20, // memberPower
        "claimWeight": 5, // claimWeight
        "powerTicks": { // If not false, enable power ticks and death penalty
            "deathPenalty": 10, // powerDeathPenalty
            "ticks": 12000, // ticksForPower
            "reward": 1 // ticksForPowerReward
        }
    },
    "safe": { // If not false, enable faction safe
        "enderChest": true, // If true, enable replacing ender chests with faction safe
        "double": true // factionSafeDouble
    },
    "home": { // If not false, enable homes
        "claimOnly": true, // If true, only allow setting home in claims
        "damageTickCooldown": 100 // safeTicksToWarp
    },
    "maxFactionSize": 0, // Use 0 for none instead of -1
    "changeChat": true, // chatModificationEnabled
    "friendlyFire": false // friendlyFireEnabled
}
```

### Describe alternatives you've considered.

- Keep the current system
- Switch to YAML/TOML
- Rework config option names

Additionally, if granular control of commands in the config is wanted, it could instead be implemented with a `permissions` option that given a command's permission key, and a boolean value can hook into the permission API and enable or disable it by default.

**Comment by BlueZeeKing** [comment]
I think some of the names should be changed, but I like the nesting

**Comment by ickerio** [comment]
I'm happy with this change. @BlueZeeKing since you've self assigned, just close the issue when you think its all ready

**Comment by BlueZeeKing** [comment]
I think that maybe one or two renames but this is good to be closed

**Comment by ickerio** [comment]
One quick change, I think `deathPenalty` should be under `power` not under `powerTicks`

**Comment by ickerio** [comment]
Also it is now not possible to have faction safes accessible only when right clicking ender chests and not using the `/f safe` command. Some servers may want this as its much more vanilla and less abusable. 

I believe it should just be simply replaced like this and if you want to disable safes, instead of `"safe": false` just set `command` and `enderChest` to false.
```js
  "safe": { 
    "command": true // If the safe command is enabled
    "enderChest": true, // If enderchests are replaced by faction safe
    "double": true // If the faction safe is a double chest
  }
```

Sorry I would do this myself but am away from my machine. I'll open this issue and I reckon we try get this done before the next release (v2.2.0) as well as my previous comment on this issue.

**Comment by PyPylia** [comment]
I initially thought about this, however, I personally believe it's cleaner if you instead use the Fabric Permissions API to disable commands. This change could definitely be implemented and would be easy to do so, however, I think it gives 'special treatment' to the `/factions safe` command over other commands, and reimplements logic that already exists.

**Comment by ickerio** [comment]
Oh true, good point I agree with you, I didn't think of the Permissions API. 

> One quick change, I think `deathPenalty` should be under `power` not under `powerTicks`

I guess just this then
