### ISSUE TITLE
Reimplement entity interact checks in claims

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#63]
### Expected behavior

Interaction with entities (such as armour stands) in claimed chunks should be prevented.

### Observed/actual behavior

Interaction with entities in claimed chunks isn't prevented.

### Steps/models to reproduce

- Summon an armour stand in a chunk claimed by a non-allied faction
- Attempt to place armour onto the armour stand

### Version

2.1.0 (1.19)

**Comment by BlueZeeKing** [comment]
I belive @LowKeyCodings fork implements this

**Comment by svr333** [comment]
I've also implemented this

**Comment by BlueZeeKing** [comment]
This is done but I think it could be a little bit more elegant. I tried to use the Fabric API but it wasn't working.

**Comment by BlueZeeKing** [comment]
Since the current method is working and I don't think anybody wants to fix it, I'm going to close this
