### ISSUE TITLE
Blacklist of faction names

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#64]
### Is your feature request related to a problem?

Currently, you can create factions with confusing names (such as Wilderness).
This could confuse other players and should be prevented.

### Describe the solution you'd like.

Add a config option that is an array of blacklisted faction names, and include `wilderness` by default.

### Describe alternatives you've considered.

Add some identifier to distinguish between Wilderness and a faction named Wilderness in radar and similar things.

### Other

Inspired by svr333/FabricFactions@a578df9e8b09dfb02c9fdb5c1955a606fb371e02

**Comment by BlueZeeKing** [comment]
Fixed this by adding a list to the config
