### ISSUE TITLE
Allow interactions outside of claim from inside claim

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#65]
### Is your feature request related to a problem?

Currently, if a player tries to interact with a block/item/entity that is outside of a claim, while they are inside a claimed chunk of a non-allied faction, it prevents them from doing so.

### Describe the solution you'd like.

Allow players to interact with blocks/items/entities that are in other chunks they have permission in.

### Describe alternatives you've considered.

None

**Comment by ickerio** [comment]
This will be dependent on our decision to support #70 or not.

**Comment by svr333** [comment]
Why does it depend on that? This can easily be done by changing every occurence of the following

```java
if (checkPermissions(player, entity.getBlockPos(), world) == ActionResult.FAIL || checkPermissions(player, player.getBlockPos(), world) == ActionResult.FAIL) {
    return ActionResult.FAIL;
}
```
 into
```java
if (checkPermissions(player, entity.getBlockPos(), world) == ActionResult.FAIL) {
    return ActionResult.FAIL;
}
```
