### ISSUE TITLE
Allow interactions that do not alter the world

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#66]
### Is your feature request related to a problem?

Currently attempting to do non-altering actions inside a non-allied faction's claimed chunk (eg. opening a crafting table, eating food) is prevented.

### Describe the solution you'd like.

Allow actions that do not alter the world.

### Describe alternatives you've considered.

Whitelist specific actions within claimed chunks

### Other

Inspired by svr333/FabricFactions@01c9d45431dd5449de4265260bfcca0f70e33ee7

**Comment by ickerio** [comment]
This will be dependent on our decision to support #70 or not.

**Comment by BlueZeeKing** [comment]
This is similar to #56

**Comment by CamperSamu** [comment]
This should be addressed by #56, not by just permitting this behavior by default.

Usually you don't want your enemies to do actions like crafting inside your territory, but something like eating food or drinking a potion _should_ be allowed.

**Comment by BlueZeeKing** [comment]
completed, commit list in #56
