### ISSUE TITLE
Improve info command

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#67]
### Is your feature request related to a problem?

Currently, the info command lacks some information and colour.

### Describe the solution you'd like.

Add colour to enemies and allies, and display the faction owner. Additionally, list the commanders and leaders somehow.

### Describe alternatives you've considered.

None

### Other

Inspired by svr333/FabricFactions@1c31983df8fcfbafb16a085719453b9b152f0acc

**Comment by svr333** [comment]
Visual example of my implementation

### Info Command
![image](https://user-images.githubusercontent.com/35664724/177210022-24350787-6906-408d-a257-a0dfc8b15c8a.png)

### Members Command
![image](https://user-images.githubusercontent.com/35664724/177210071-557093b4-f052-4111-b34d-94628bed8ec1.png)


There is probably room for improvement here as well, but personally I like this a lot better than the one that was originally implemented

**Comment by BlueZeeKing** [comment]
I think this is much better than the old one. I also like the addition of a `/f members` command

**Comment by svr333** [comment]
I'll try to get a PR in later today then
