### ISSUE TITLE
Feature request: Claim list and remove all commands

### ISSUE THREAD

**Issue by CalXee** [ickerio/factions#7]
Self explanatory, in case you don't want to disband a faction but want to remove all claims.

**Comment by ickerio** [comment]
Adding onto this issue, I want a `/f claim list` command as well

**Comment by CalXee** [comment]
If ``/f claim list`` works by showing chunk coordinates, then I think it should only show particles around claimed chunks if ``/gamerule reducedDebugInfo`` is set to true.
