### ISSUE TITLE
Guest member rank

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#78]
### Is your feature request related to a problem?

Currently, when playing in untrusted/public environments, factions may want to add untrusted members and give primitive permissions to those members, until they prove their trustworthiness. Under the current system, untrusted members are given too much power, which leads to our mod being lacklustre for use on public servers.

### Describe the solution you'd like.

Add another rank below the `Member` rank, which I suggest the name `Guest`. These members would be able to interact with blocks and entities within the faction's claims, but not place or break blocks, use the faction safe, etc... The exact permissions could possibly be configurable within the config, or on a per faction basis by Leaders/Owners.

### Describe alternatives you've considered.

Configuring permissions on a per-player basis is also possible, but this has been suggested in the past and was deemed too niche.

**Comment by BlueZeeKing** [comment]
Completed in 576d74e48af503ed523f6ac52674d25254771774
