### ISSUE TITLE
More config options. Change default faction TAG. Add TAG to player nickname above head

### ISSUE THREAD

**Issue by crypt0ende** [ickerio/factions#80]
Is it possible to add more config options, like:

- change or disable FACTIONLESS tag; 
- visible tag on top of player model (like team tag)
- disable chat messages about power points in chat and disable point system at all;
- placeholder for team tag, team chat for other chat, tab formatting mods that use Placeholder API;
- disable HOME and other teleport options, to make factions more hardcore

**Comment by BlueZeeKing** [comment]
What do you mean by "team chat for other chat"? The home system can already be disabled with the current config by setting the `home` field to false. The power system can also be effectively disabled by setting all the power options to 0 except for `ticks`. A visible tag above players would most likely have to be the role of another mod that supports the Placeholder API.

**Comment by BlueZeeKing** [comment]
We can add a placeholder with that has the faction name without the FACTIONLESS tag

**Comment by crypt0ende** [comment]
> team chat for other chat

I mean chat and tab formatting mods, specifically Styled Chat, Styled Player List. Also, does war work? How will it act without point system?

**Comment by crypt0ende** [comment]
> We can add a placeholder with that has the faction name without the FACTIONLESS tag

Thanks for your work

**Comment by BlueZeeKing** [comment]
> We can add a placeholder with that has the faction name without the FACTIONLESS tag

I just looked back through the code and the faction name placeholder doesn't have the factionless tag. If you wanted to make the tab list not include the factionless tag you can disable the tab menu from the factions mod in the config (`factions.json > display > tabMenu = false`), then use another tab mod (Styled Player List)

**Comment by BlueZeeKing** [comment]
> Also, does war work? How will it act without point system?

War isn't implemented yet
