### ISSUE TITLE
Drop safe items on faction disband

### ISSUE THREAD

**Issue by BlueZeeKing** [ickerio/factions#86]
### Is your feature request related to a problem?

Items in the safe are deleted when a faction is disbanded instead of dropping

### Describe the solution you'd like.

Drop the items on the person who disbanded the faction

### Describe alternatives you've considered.

Ask for confirmation before deleting items or prevent the faction from being deleted without emptying the safe

**Comment by ickerio** [comment]
Agreed. Player who disbands the clan should have the items put in their inventory then the surplus dropped around them. A warning/confirmation of this behavior is also necessary imo

**Comment by BlueZeeKing** [comment]
done in b10f144e5a7f3e4b1b13b4dfdbaaca858f2f97e5
