### ISSUE TITLE
Official way to disable claim protection

### ISSUE THREAD

**Issue by PyPylia** [ickerio/factions#89]
### Is your feature request related to a problem?

Lots of people want to use the claim system, but don't want any of the grief prevention it provides.

### Describe the solution you'd like.

Possibly allow you to set `"power"` to `false`, or perhaps a more verbose way.

### Describe alternatives you've considered.

Currently you can set faction power to 0, but this requires manually resetting power (which we should also fix), and requires adding `force` when trying to claim. It also allows claiming over other claims.

**Comment by PyPylia** [comment]
Actually setting `"power"` to `false` could be interpreted as disabling claims, so we should add a boolean toggle to enable or disable grief prevention.

**Comment by BlueZeeKing** [comment]
Done
