### ISSUE TITLE
scoreboard objective

### ISSUE THREAD

**Issue by Dizover** [ickerio/factions#90]
### Is your feature request related to a problem?

scoreboard objectives of player faction would allow to see faction above player head which would be very convenient for determining the faction to which the player belongs.

### Describe the solution you'd like.

scoreboard objectives of player faction, something similar is implemented in this mod - [fabric-rep-system](https://github.com/modrinth-smp/fabric-rep-system)

### Describe alternatives you've considered.

There are no alternatives.

**Comment by BlueZeeKing** [comment]
I don't think using the vanilla scoreboard and objective system would work because score are all numbers and cannot be strings. I look into other methods of putting the faction name above players heads but I can't make an promises into if it's possible.

**Comment by ickerio** [comment]
I think this is an issue that the Placeholder API can solve. I don’t think we need to add this ourselves

**Comment by BlueZeeKing** [comment]
I agree
