### ISSUE TITLE
Option to disable /faction home

### ISSUE THREAD

**Issue by fennecr** [ickerio/factions#91]
### Is your feature request related to a problem?

I run a vanilla-like server with a teleportation system that requires energy, /factions home makes this feature irrelevant.

### Describe the solution you'd like.

I'd like to be able to disable /factions home.

### Describe alternatives you've considered.

Our only other alternative is to not use factions.

**Comment by PyPylia** [comment]
Please read our [config documentation](https://github.com/ickerio/factions/wiki/Config).
You can disable the `/factions home` command by setting `"home"` to `false` in the `factions.json` file found in the config folder.
Here's an example:
```json
{
  "version": 3,
  "power": {
    "base": 20,
    "member": 20,
    "claimWeight": 5,
    "deathPenalty": 10,
    "powerTicks": {
      "ticks": 12000,
      "reward": 1
    }
  },
  "safe": {
    "enderChest": true,
    "double": true
  },
  "home": false,
  "display": {
    "factionNameMaxLength": -1,
    "changeChat": true,
    "tabMenu": true,
    "nameBlackList": [
      "wilderness",
      "factionless"
    ]
  },
  "relationships": {
    "allyOverridesPermissions": true,
    "defaultGuestPermissions": ["USE_BLOCKS", "USE_ENTITIES"]
  },
  "maxFactionSize": -1,
  "friendlyFire": false,
  "requiredBypassLevel": 2
}
```
I am closing this issue as resolved now, if this does not solve your problem, please reopen the issue with more details.
