### ISSUE TITLE
Chat suggestion

### ISSUE THREAD

**Issue by KingBones314** [ickerio/factions#97]
### Is your feature request related to a problem?

I have the factions reward system set to 5 points every 15 minutes, so the chat message saying "[player] has recieved 5 points for surviving" will appear every 15 minutes. I would like to be able to just get rid of the chat message.

### Describe the solution you'd like.

A command to disable the chat message for when someone recieves a point for surviving. 

### Describe alternatives you've considered.

Originally I had it set to 1 point every 5 minutes which got annoying quicly so I rasied it to 5 every 15 minutes. I know I can raise the amount of time even more, but the players on my server don't stay on for long intervals and would like to keep the current rate.

**Comment by BlueZeeKing** [comment]
This could be combined into #87 and add a black list for messages that won't be sent
